INFO 2024-10-03 11:25:04,635 django.utils.autoreload MainThread 8441262656 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 51173 Watching for file changes with StatReloader
INFO 2024-10-03 11:25:39,917 django.utils.autoreload MainThread 8441262656 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 51241 Watching for file changes with StatReloader
INFO 2024-10-03 11:25:55,487 django.utils.autoreload MainThread 8441262656 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 51283 Watching for file changes with StatReloader
INFO 2024-10-03 11:28:11,046 django.utils.autoreload MainThread 8441262656 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 51530 Watching for file changes with StatReloader
ERROR 2024-10-03 11:28:20,103 django.request Thread-6 (process_request_thread) 6224785408 log log.py 241 django.request log_response 51530 Internal Server Error: /
Traceback (most recent call last):
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_site

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/contrib/sites/middleware.py", line 12, in process_request
    request.site = get_current_site(request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/contrib/sites/shortcuts.py", line 16, in get_current_site
    return Site.objects.get_current(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/contrib/sites/models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_site
ERROR 2024-10-03 11:28:20,109 django.server Thread-6 (process_request_thread) 6224785408 basehttp basehttp.py 212 django.server log_message 51530 "GET / HTTP/1.1" 500 19811
ERROR 2024-10-03 11:28:20,282 django.request Thread-6 (process_request_thread) 6224785408 log log.py 241 django.request log_response 51530 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_site

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/contrib/sites/middleware.py", line 12, in process_request
    request.site = get_current_site(request)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/contrib/sites/shortcuts.py", line 16, in get_current_site
    return Site.objects.get_current(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/contrib/sites/models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/johnsolly/code/awesome-django-blog/.venv/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_site
ERROR 2024-10-03 11:28:20,285 django.server Thread-6 (process_request_thread) 6224785408 basehttp basehttp.py 212 django.server log_message 51530 "GET /favicon.ico HTTP/1.1" 500 19786
INFO 2024-10-03 11:28:57,371 django.utils.autoreload MainThread 8441262656 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 51605 Watching for file changes with StatReloader
INFO 2024-10-03 11:28:59,500 django.server Thread-1 (process_request_thread) 6165491712 basehttp basehttp.py 212 django.server log_message 51605 "GET / HTTP/1.1" 200 5107
INFO 2024-10-03 11:28:59,517 django.server Thread-2 (process_request_thread) 12901707776 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/svg/man-avatar.svg HTTP/1.1" 200 2250
INFO 2024-10-03 11:28:59,518 django.server Thread-1 (process_request_thread) 6165491712 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/css/main.css HTTP/1.1" 200 26444
INFO 2024-10-03 11:28:59,518 django.server Thread-3 (process_request_thread) 12918534144 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/svg/chatbox-icon.svg HTTP/1.1" 200 1276
INFO 2024-10-03 11:28:59,520 django.server Thread-3 (process_request_thread) 12918534144 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/logo_transparent_cropped.webp HTTP/1.1" 200 4504
INFO 2024-10-03 11:28:59,520 django.server Thread-4 (process_request_thread) 12935360512 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/js/htmx.min.js HTTP/1.1" 200 44307
INFO 2024-10-03 11:28:59,522 django.server Thread-1 (process_request_thread) 6165491712 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/jsolly.webp HTTP/1.1" 200 254412
INFO 2024-10-03 11:28:59,530 django.server Thread-2 (process_request_thread) 12901707776 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/svg/comment-icon.svg HTTP/1.1" 200 718
INFO 2024-10-03 11:28:59,530 django.server Thread-3 (process_request_thread) 12918534144 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/js/header.js HTTP/1.1" 200 672
INFO 2024-10-03 11:28:59,531 django.server Thread-5 (process_request_thread) 12952186880 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/svg/scroll-to-top.svg HTTP/1.1" 200 490
INFO 2024-10-03 11:28:59,531 django.server Thread-4 (process_request_thread) 12935360512 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/js/chatbox.js HTTP/1.1" 200 2253
INFO 2024-10-03 11:28:59,531 django.server Thread-1 (process_request_thread) 6165491712 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/svg/clock.svg HTTP/1.1" 200 269
INFO 2024-10-03 11:28:59,584 django.server Thread-1 (process_request_thread) 6165491712 basehttp basehttp.py 212 django.server log_message 51605 "GET /media/default.webp HTTP/1.1" 200 135
INFO 2024-10-03 11:28:59,585 django.server Thread-5 (process_request_thread) 12952186880 basehttp basehttp.py 212 django.server log_message 51605 "GET /static/favicon/favicon-32x32.webp HTTP/1.1" 200 852
INFO 2024-10-03 17:51:15,628 django.utils.autoreload MainThread 8441262656 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 65926 Watching for file changes with StatReloader
INFO 2024-10-03 17:51:20,755 django.server Thread-1 (process_request_thread) 6207598592 basehttp basehttp.py 212 django.server log_message 65926 "GET / HTTP/1.1" 200 5063
INFO 2024-10-12 14:35:11,386 django.utils.autoreload MainThread 8196502080 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 64172 Watching for file changes with StatReloader
INFO 2024-10-12 14:35:52,537 django.utils.autoreload MainThread 8196502080 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 64331 Watching for file changes with StatReloader
INFO 2024-10-12 14:36:40,689 django.utils.autoreload MainThread 8196502080 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 64367 Watching for file changes with StatReloader
INFO 2024-10-12 14:36:43,635 django.server Thread-1 (process_request_thread) 6196359168 basehttp basehttp.py 212 django.server log_message 64367 "GET / HTTP/1.1" 200 5090
INFO 2024-10-12 14:36:43,653 django.server Thread-1 (process_request_thread) 6196359168 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/css/main.css HTTP/1.1" 304 0
INFO 2024-10-12 14:36:43,659 django.server Thread-2 (process_request_thread) 6213185536 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/js/htmx.min.js HTTP/1.1" 200 44307
INFO 2024-10-12 14:36:43,664 django.server Thread-1 (process_request_thread) 6196359168 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/svg/man-avatar.svg HTTP/1.1" 304 0
INFO 2024-10-12 14:36:43,665 django.server Thread-3 (process_request_thread) 6230011904 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/svg/chatbox-icon.svg HTTP/1.1" 304 0
INFO 2024-10-12 14:36:43,665 django.server Thread-4 (process_request_thread) 6246838272 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/svg/clock.svg HTTP/1.1" 304 0
INFO 2024-10-12 14:36:43,666 django.server Thread-6 (process_request_thread) 6280491008 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/logo_transparent_cropped.webp HTTP/1.1" 304 0
INFO 2024-10-12 14:36:43,667 django.server Thread-1 (process_request_thread) 6196359168 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/js/header.js HTTP/1.1" 304 0
INFO 2024-10-12 14:36:43,668 django.server Thread-5 (process_request_thread) 6263664640 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/js/chatbox.js HTTP/1.1" 304 0
INFO 2024-10-12 14:36:43,671 django.server Thread-3 (process_request_thread) 6230011904 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/svg/comment-icon.svg HTTP/1.1" 304 0
INFO 2024-10-12 14:36:43,672 django.server Thread-6 (process_request_thread) 6280491008 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/svg/scroll-to-top.svg HTTP/1.1" 304 0
INFO 2024-10-12 14:36:43,673 django.server Thread-2 (process_request_thread) 6213185536 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/jsolly.webp HTTP/1.1" 200 254412
INFO 2024-10-12 14:36:43,717 django.server Thread-2 (process_request_thread) 6213185536 basehttp basehttp.py 212 django.server log_message 64367 "GET /media/default.webp HTTP/1.1" 304 0
INFO 2024-10-12 14:36:43,730 django.server Thread-2 (process_request_thread) 6213185536 basehttp basehttp.py 212 django.server log_message 64367 "GET /static/favicon/favicon-32x32.webp HTTP/1.1" 304 0
INFO 2024-10-12 14:36:46,003 django.server Thread-2 (process_request_thread) 6213185536 basehttp basehttp.py 212 django.server log_message 64367 "GET / HTTP/1.1" 200 5054
INFO 2024-10-12 14:38:16,403 django.utils.autoreload MainThread 8196502080 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 64555 Watching for file changes with StatReloader
INFO 2024-10-12 14:51:59,972 django.utils.autoreload MainThread 8196502080 autoreload autoreload.py 668 django.utils.autoreload run_with_reloader 65239 Watching for file changes with StatReloader
INFO 2024-10-12 14:52:03,455 django.server Thread-6 (process_request_thread) 6233010176 basehttp basehttp.py 212 django.server log_message 65239 "GET / HTTP/1.1" 200 5155
